name: 'DDF Validator action'
description: 'Validate all DDf in directory.'
author: 'Zehir'
inputs:
  directory:
    required: true
    description: 'input directory'
  search:
    required: false
    description: 'input search pattern'
    default: '**/*.json'
  ignore:
    required: false
    description: 'ignore files that match this pattern'
runs:
  using: 'node16'
  main: 'dist/index.js'
